# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "ckeditor"
    js_path:   "ckeditor/ckeditor.js"
    configs:
        main:
            height: 200
            removeButtons: 'Anchor,Copy,Cut,Paste,Subscript,Superscript,Undo,Redo,Indent,Outdent,About'
            removeDialogTabs: 'link:advanced;link:target'
            forceEnterMode: true
            entities_latin: false
            disableNativeSpellChecker: false
            wordcount:
                maxCharCount: 2000
                showWordCount: true
                showCharCount: true
                countHTML: true
                countSpacesAsChars: false
                countBytesAsChars: false
                countLineBreaks: true
                showParagraphs: false
            title: false
            dialog_backgroundCoverColor: 'rgb(20,20,20)'

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'common/form/ckeditor.html.twig'
