# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    error_controller: App\Controller\DarkErrorController::showError
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    request:
        formats:
            pdf: application/pdf
            csv: text/csv
            ods: application/vnd.oasis.opendocument.spreadsheet
            xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

    html_sanitizer:
        sanitizers:
            default:
                allow_elements: { a: '*', b: '*', br: '*', div: '*', em: '*', i: '*', p: '*', span: '*', strong: '*', sub: '*', sup: '*', u: '*', ul: '*', ol: '*', li: '*' }

                # allowing all protocols would make more sense until CKEditor 4 is used but:
                # https://github.com/symfony/symfony/issues/49030
                allowed_link_schemes: ['http', 'https', 'mailto', 'tel', 'ftp', 'ftps', 'news']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
