security:
    providers:
        database:
            entity:
                class: App\Entity\User
                property: name

    encoders:
        rl_v2:
            algorithm: bcrypt
            cost: 12
        rl_v1:
            id: App\Security\RLv1Encoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: session_login
                check_path: session_login
                default_target_path: user_radiotables
                username_parameter: session_log_in[username]
                password_parameter: session_log_in[password]
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: session_log_in[_token]
                csrf_token_id: session_log_in
            logout:
                path: session_logout
                target: homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800   # 1 week.
                remember_me_parameter: session_log_in[rememberMe]
