security:
    providers:
        database:
            entity:
                class: App\Entity\User
                property: name

    encoders:
        rl_v2:
            algorithm: bcrypt
        rl_v1:
            algorithm: sha1

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: session_login
                check_path: session_login
                default_target_path: user_radiotables
            logout:
                path: session_logout
                target: homepage
