security:
    providers:
        database:
            entity:
                class: App\Entity\User
                property: name

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        rl_v1:
            id: App\Security\Encoder\RLv1Encoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: security.login
                check_path: security.login
                default_target_path: user.my_radiotables
                username_parameter: security_login[username]
                password_parameter: security_login[password]
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: security_login[_token]
                csrf_token_id: security_login
            logout:
                path: security.logout
                target: homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800   # 1 week.
                remember_me_parameter: security_login[rememberMe]

    # Required for App\EventListener\RehashRLv1UserPassword.
    erase_credentials: false
