twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'common/form/overwritten_types.html.twig'
        - 'common/form/custom_types.html.twig'
    globals:
        app_version: '%app.version%'
        app_development: '%env(default::bool:DEVELOPMENT_WARNING)%'

when@test:
    twig:
        strict_variables: true
