twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        format: 'j F Y'
    form_themes:
        - 'form/overwritten_types.html.twig'
        - 'form/custom_types.html.twig'

    # number_format defaults for radiostation frequency and power.
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ''
