version: '3.7'

services:
    http:
        build: '.docker/apache'
        ports:
            - '80:80'
        volumes:
            - './public:/srv/app/public'

    app:
        build: '.docker/php-fpm'
        environment:
            DATABASE_URL: mysql://radiolista:radiolista@db:3306/radiolista
        volumes:
            - '.:/srv/app'
            - './.docker/data/var:/srv/app/var'

    db:
        image: 'mariadb:10.4'
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
            MYSQL_USER: 'radiolista'
            MYSQL_PASSWORD: 'radiolista'
            MYSQL_DATABASE: 'radiolista'
        volumes:
            - './.docker/data/db:/var/lib/mysql'
