version: '3.7'

services:
    http:
        build: '.docker/apache'
        ports:
            - '80:80'
        volumes:
            - './public:/srv/app/public'
        depends_on:
            - app

    app:
        build: '.docker/php-fpm'
        environment:
            DATABASE_URL: mysql://root:toor@db:3306/radiolista
        volumes:
            - '.:/srv/app'
            - './.docker/data/var:/srv/app/var'
        depends_on:
            - db

    db:
        image: 'mariadb:10.4'
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
        volumes:
            - './.docker/data/db:/var/lib/mysql'
