version: '3.3'

services:
    http:
        build: 'container/apache'
        ports:
            - '2012:80'
        volumes:
            - '.:/srv:z'

    app:
        build: 'container/php-fpm'
        environment:
            DATABASE_URL: 'mysql://root:toor@db:3306/radiolista-v3?server_version=5.7'
        volumes:
            - '.:/srv:z'

    js:
        build: 'container/npm'
        volumes:
            - '.:/srv:z'

    db:
        image: 'mysql:5.7'
        ports:
            - '2013:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
        volumes:
            - './var/mysql:/var/lib/mysql:z'
