version: '3.7'

services:
    http:
        build: '.container/apache'
        ports:
            - '2012:80'
        volumes:
            - './public:/srv/app/public:z'

    app:
        build: '.container/php-fpm'
        environment:
            DATABASE_URL: mysql://root:toor@db:3306/radiolista-v3
        volumes:
            - '.:/srv/app:z'
            - './.container/data/var:/srv/app/var:z'

    db:
        image: 'mariadb:10.4'
        ports:
            - '2013:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
        volumes:
            - './.container/data/db:/var/lib/mysql:z'
