<?php

namespace App\Util;

class PdfMetadataPatcher
{
    /**
     * Removes "Producer" metadata field and replaces "Creator" one with provided text.
     * Designed to patch documents generated by wkhtmltopdf.
     */
    public function replaceCreatorMetadata(string $pdf, string $creator): string
    {
        $this->replaceCreator($pdf, $creator, $this->removeProducer($pdf));

        return $pdf;
    }

    private function removeProducer(string &$pdf): int
    {
        $removedLength = 0;

        $pdf = preg_replace_callback(
            '#/Producer \((.*)\)#',
            function(array $matches) use (&$removedLength) {
                $removedLength = strlen($matches[0]);

                return '';
            },
            $pdf,
            1
        );

        return $removedLength;
    }

    private function replaceCreator(string &$pdf, string $creator, int $extraLength): void
    {
        $pdf = preg_replace_callback(
            '#/Creator \((.*)\)#',
            function(array $matches) use ($creator, $extraLength) {
                $creator = substr($this->encodeString($creator), 0, strlen($matches[1]) + $extraLength);

                return str_pad(
                    str_replace($matches[1], $creator, $matches[0]),
                    strlen($matches[0]) + $extraLength
                );
            },
            $pdf,
            1
        );
    }

    private function encodeString(string $string): string
    {
        $string = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $string);

        return "\xFE\xFF" . mb_convert_encoding($string, 'UTF-16BE', 'UTF-8');
    }
}
