services:
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        autoconfigure: false

    App\DataFixtures\TestsFixtures:
        autoconfigure: true

    test.client:
        class: App\Tests\KernelBrowser
        autowire: true
        public: true
