name: Check security

on:
    push:
        branches: ['*']
    schedule:
        - cron: '0 6 * * *'

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code
              uses: actions/checkout@v2

            - name: Fetch checker
              run: wget https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -O security-checker && chmod +x security-checker

            - name: Run security checker
              run: ./security-checker
