name: Run test suite

on:
  push:
    branches: ['*']

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                extensions: intl, pdo_sqlite

            - name: Install dependencies
              run: composer install --no-progress --no-suggest --no-interaction

            - name: Run test suite
              run: bin/phpunit --testdox
