#!/bin/bash -e

name=radiolista-v3
port=2012

if podman pod exists $name; then
    echo 'Pod '$name' already exists. Use `podman pod start '$name'` to start'
    echo 'or use `podman pod rm '$name' --force` to remove all containers.'
    exit 1
fi

cd $(dirname "$0")

podman pod create --name $name \
    --publish $port':80' --publish $(( port + 1 ))':3306'

podman build --tag $name'_http' 'apache'
podman build --tag $name'_app' 'php-fpm'

# --add-host switch is used only for compatibility with docker-compose.

podman create --pod $name --name $name'_http' --add-host 'http:127.0.0.1' \
    --volume '../public:/srv/app/public:z' \
    $name'_http'

podman create --pod $name --name $name'_app' --add-host 'app:127.0.0.1' \
    --env 'DATABASE_URL=mysql://root:toor@db:3306/'$name'?server_version=5.7' \
    --volume '..:/srv/app:z' \
    --volume './data/var:/srv/app/var:z' \
    $name'_app'

podman create --pod $name --name $name'_db' --add-host 'db:127.0.0.1' \
    --env 'MYSQL_ROOT_PASSWORD=toor' \
    --volume './data/db:/var/lib/mysql:z' \
    'mysql:5.7'

echo
echo 'Done! Use `podman pod start '$name'` to start the application.'
echo 'Then, go to http://127.0.0.1:'$port' in the browser.'
echo 'Application database is available on 127.0.0.1:'$(( port + 1 ))'.'
echo
